### PR TITLE
feat: add state context mock

### PR DESCRIPTION
**Pull request by aymeric-duchein**
Hi! 😄 
This PR adds a new tool to test functions with the  `@Action` decorator.
This is a follow up to my message in https://github.com/ngxs-labs/testing/issues/1 so I won't re-post all the explainations here. 
This PR needs a version of `@ngxs/store` above this commit https://github.com/ngxs/store/commit/ea5e70fc97be8a47bb244ca05de89e0fb504ef83 in order to use the injection token for the `StateContextFactory`.

If you need an example on how to use this new function you can check the test.

I tried to follow the existing code style but feel free to tell me if something needs to change!

### CODE REVIEW

**Review by splincode — COMMENTED** [review]
I would wait for release 3.6.0

**Comment by aymeric-duchein** [comment]
Updated with version 3.6.0

**Comment by splincode** [comment]
I will publish later

**Comment by aymeric-duchein** [comment]
Thank you!

**Comment by splincode** [comment]
@aymeric-duchein also you send pull request with update REAMDE.md

**Pull request merged**
